

<br><br>
<table cellpadding="0" cellspacing="0"><tr><td>
<font face="News Topic MT" size="3" color="black">
<form action="<?php $REQUEST_URL; ?>" method="POST">
<input type="hidden" name="login">
<table border="0" cellpadding="5">
Username:<input name="username" type="text" size="15"><br>
Password:<input name="passw" type="password" size="15">
<input type="submit" value="Login"></table>
</form>
</tr></td></table>







