<form action="register.php" method="POST">
<input type="hidden" name="register">

<table border="0" cellpadding="5">
					<!-- 70 -->
Username:<br><input name="username" type="text" size="15"><br><br>

Password:<br><input name="pw" type="password" size="15"><br><br>

Re-type Password:<br><input name="pw2" type="password" size="15"><br><br>

Email Address:<br><input name="email" type="text" size="15"><br><br>

<input type="submit" value="Submit"></table>
</form>